### ISSUE TITLE
hey, Could you upload the cfg file that you mentioned in the training ohem scripts?

### ISSUE THREAD

**Issue by weitaoatvison** [abhi2610/ohem#1]
hey, I have download your code and I want to have a try, However, I found in your experiments/ directory there are no directory called cfg, but in your training scripts experiments/scripts/faster-rcnn-ohem.sh you have mentioned it. So could you upload your cfg file?

**Comment by morusu** [comment]
did you have the models file： models/pascal_voc/VGG_CNN_M_1024/fast_rcnn_ohem/solver.prototxt ?

**Comment by zimenglan-sysu-512** [comment]
@weitaoatvison @morusu  i just refer to `lib/roi_data_layer/layer.py` and `lib/roi_data_layer/minibatch.py` and find out how `ohem` implement. thanks.

**Comment by weitaoatvison** [comment]
@zimenglan-sysu-512 Thanks for your advice. And do you have the solver.prototxt or train_val.prototxt of OHEM training. I still a little confused about how it be used. Thanks!

**Comment by zimenglan-sysu-512** [comment]
@weitaoatvison @morusu ，i have tried incroporated the ohem code (mainly as i mentioned before) into faster-rcnn, and write the solver.pt, train.pt, test.pt and corresponding yml files, and run two experiments (nms and without nms), i found that the results is not good (65.4%, 66.6%), lower than the origin  faster-rcnn (69.6%). i don't know why i get such results.
@abhi2610 can you share the corresponding files? i also implement ohem in my way, the best results is 71.1 mAP, just a litter higher than the origin.

**Comment by weitaoatvison** [comment]
@zimenglan-sysu-512  How did you train it on faster-rcnn, it seems it should be trained as alter training method that @abhi2610 metioned in the end of the repository.

**Comment by zimenglan-sysu-512** [comment]
@weitaoatvison i train it using end2end method, it seems it's hard to train it.

**Comment by zimenglan-sysu-512** [comment]
@weitaoatvison @morusu here're my files, i am not sure that they are in the right place.
[my_ohem.tar.gz](https://github.com/abhi2610/ohem/files/440512/my_ohem.tar.gz)

**Comment by weitaoatvison** [comment]
@zimenglan-sysu-512 I will try to train it and share the results. And this train.prototxt can achieve the ap of 65.4% and 66.6%?

**Comment by zimenglan-sysu-512** [comment]
@weitaoatvison i use end2end style, and achieve 70.4% mAP.

**Comment by morusu** [comment]
@zimenglan-sysu-512 use the shared prototxt and achieve 70.4% mAP ? I try the alternative method but don't achieve the desired result compared to end-to-end methon on myself data

**Comment by zimenglan-sysu-512** [comment]
@morusu yes. can you share your results?

**Comment by morusu** [comment]
@zimenglan-sysu-512 I use faster-rcnn to detect only one classe, faster-rcnn in end-to-end can achieve 88.7% but faster-rcnn in alternative method only achieve 85.2%, alternative methond with ohem achieve 86.7%.

**Comment by abhi2610** [comment]
Sorry, I forgot to upload the prototxt and yml for OHEM models; and I wasn't monitoring the repository. Thanks for Ren for emailing me.

Please check the latest commit.

**Comment by abhi2610** [comment]
@ all lets move the Faster R-CNN discussion to a new thread.
