### ISSUE TITLE
How to write the layer prototxt in python with duplicate propagate_down=false  

### ISSUE THREAD

**Issue by whcjb** [abhi2610/ohem#3]
what if I want to write this when use the Net_spec() in python ?
`layer{`
  `name: "m3@ssh_output_ohem"`
 ` type: "Concat"`
 ` bottom: "m3@ssh_3x3_output_ohem"`
  `bottom: "m3@ssh_5x5_output_ohem"`
  `bottom: "m3@ssh_7x7_output_ohem"`
  `top: "m3@ssh_output_ohem"`
  `concat_param{`
      `axis: 1`
  `}`
  `propagate_down: false`
  `propagate_down: false`
  `propagate_down: false`
`}`
There are three#  **`propagate_down: false`**, and python can not receive the duplicate args.
How to write in python?

**Comment by abhi2610** [comment]
Hello, The question is better addressed to caffe-users mailing list.
