### ISSUE TITLE
F0116 07:59:24.649296 18466 roi_pooling_layer.cu:91] Check failed: error == cudaSuccess (9 vs. 0)  invalid configuration argument

### ISSUE THREAD

**Issue by blueardour** [abhi2610/ohem#4]
Hi, I met a problem when testing the ohem.

I found some similar talk about it 
[https://github.com/rbgirshick/py-faster-rcnn/issues/2](https://github.com/rbgirshick/py-faster-rcnn/issues/2)

[https://github.com/D-X-Y/caffe-faster-rcnn/issues/34] (https://github.com/D-X-Y/caffe-faster-rcnn/issues/34)

By changing the GPU_NMS=False didn't help.

Also when compile, it showed my GPU was sm_35 computing compatible. So it might not caused by this problem.
` ............... `
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found gflags  (include: /usr/local/include, library: /usr/local/lib/libgflags.a)
-- Found glog    (include: /usr/local/include, library: /usr/local/lib/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
HDF5_ROOT:
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Found lmdb    (include: /usr/local/include, library: /usr/local/lib/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libsnappy.so)
-- CUDA detected: 8.0
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_35
-- OpenCV found (/usr/local/share/OpenCV)

Training and test of the py-faster-rcnn project is OK on the same machine. Training of the ohem also succeed. The problem only occurs at test phase.

Any hints about this issue or how to work around?

**Comment by abhi2610** [comment]
Yes, the issue is probably caffe compatibility with or support for CUDA < 3.0. Please see the following links for help: [Faster R-CNN issue](https://github.com/ShaoqingRen/faster_rcnn/issues/37), [Caffe issue](https://github.com/BVLC/caffe/pull/5002). or caffe-users mailing list.

Thanks!

**Comment by Flames60** [comment]
Hi, have you solved this problem? I meet the same one when testing py-faster-rcnn.
